### ISSUE TITLE
Reference pattern

### ISSUE THREAD

**Issue by csarven** [reni99/bachelor-thesis-2015#8]
I suggest using Springer's LNCS for the references e.g.,, a paper published in some conference proceedings is along the lines of: `Authors, Title, Proceedings, Year, URI`.

See also:
- http://www.springer.com/computer/lncs?SGWID=0-164-6-793341-0
- http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fspringer-lecture-notes-in-computer-science

**Comment by reni99** [comment]
I have a style guide I should stick to from the BFH. According to them I should use: <code>Authors, year, title, URI, last visit of the page</code>
